# Generated by Django 4.0.3 on 2022-04-06 07:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
