# Generated by Django 4.0.3 on 2022-04-06 07:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='text_for_done_button',
            field=models.CharField(default='Not done', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='color',
            field=colorfield.fields.ColorField(default='blue', image_field=None, max_length=18, samples=None),
        ),
    ]
